---

# Apache2.4インストール
- name: install httpd
  yum: name=httpd state=present

- name: mkdir /mnt/log/httpd
  file: >
    path=/mnt/log/httpd
    owner=root
    group=root
    state=directory

- name: configure log rotation
  copy: >
    src=logrotate-apache.conf
    dest=/etc/logrotate.d/httpd

